# Generated by Django 3.2 on 2021-04-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
